from . import inherit_account_move
from . import inherit_account_move_line
from . import inherit_account_payment
from . import pdf_viewer
from . import historial_transaccion
from . import rastreo_payment
from . import inherit_account_group
from . import inherit_analytic_account
from . import inherit_analytic_group
