{
    'name': 'Facturacion Computarizada Bolivia',
    'version': '2.0',
    'category': 'Contabilidad',
    'description': '''
            Este Modulo cumple con Todos los requisitos para realizar una "Factura Computarizada Bolivia "
         ''',
    'summary': 'Con este Modulo se podra realizar la "Factura Computarizada Bolivia',
    'sequence': '10',
    'author': 'Henry Paco Delgadillo',
    'maintainer': 'soluciones digitales para el comercio internacional',
    'depends': ['account','sale','purchase','base'],
    'data': [
        'view/template_report_layout.xml',
        'view/action_manager_fact.xml',
        'view/heredar_diario_venta.xml',
        'view/heredad_factura_venta.xml',
        'view/heredar_factura_compra.xml',
        'view/heredar_order_compra.xml',
        'wizard/wizard_venta.xml',
        'wizard/wizard_venta_txt.xml',
        'wizard/wizard_compra.xml',
        'reports/reporte_factura_pdf.xml',
        'view/heredar_a_contactos.xml',
        'test/prueba_factura_computarizada.xml',
        'security/ir.model.access.csv',
        'wizard/inherit_account_move.xml',
        'security/create_grupo_facturacion_computarizada.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}