{
    'name': 'Facturacion en Linea Bolivia',
    'version': '1.0',
    'category': 'Contabilidad',
    'description': '''
            Este Modulo cumple con Todos los requisitos para realizar una "Factura Electronica en linea Bolivia
         ''',
    'summary': 'Con este Modulo se podra realizar la "Factura Electronica en Linea Bolivia',
    'sequence': '10',
    'author': 'Sodigitalim',
    'maintainer': 'soluciones digitales para Impulsar su Negocio',
    'depends': ['account', 'point_of_sale', 'sale', 'base', 'bi_automated_sale_order', 'sd_message_personalized'],
    'data': [
        'security/create_grupo_facturacion_electronica_linea.xml',
        'security/ir.model.access.csv',
        'wizard/wizard_verificar_factura.xml',
        'view/heredar_diario_venta.xml',
        'view/heredar_a_contactos.xml',
        'view/heredar_account_move.xml',
        'view/product_service_siat.xml',
        'view/mensaje_service_siat.xml',
        'view/evento_significativo_siat.xml',
        'view/punto_venta_siat.xml',
        'view/inherit_uom_uom.xml',
        'view/inherit_product_category.xml',
        'view/heredar_product_product.xml',
        'view/siat_emision_paquete_offline.xml',
        'view/siat_emision_masiva.xml',
        'view/siat_motivos_anulacion.xml',
        'view/siat_leyenda_factura.xml',
        'view/siat_metodo_pago_service.xml',
        'view/siat_sucursal_factura.xml',
        'view/electronic_billing.xml',
        'view/inherit_pos_payment_method.xml',
        'view/inherit_sale_order.xml',
        'view/assets.xml',
        'view/template_inherit_js_pos.xml',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/data_metodo_pago.xml',
        'data/regla_registro_siat.xml',
        'wizard/anular_factura.xml',
        'wizard/wizard_pagos_factura_masiva.xml',
        'wizard/wizard_modo_offline.xml',
        'wizard/wizard_evento_significativo.xml',
        'wizard/wizard_paquete_facturas.xml',
    ],
    'qweb': [
        'static/src/xml/inherit_clientDetails_pos.xml'
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
