{
    'name': 'Modulo Contabilidad Mejoras',
    'version': '13.0.0.1',
    'category': 'Contabilidad',
    'summary': 'Mejoras del Modulo contable, Facturas, Libro mayor y demas',
    'sequence': '10',
    'author': 'Sodigitalim',
    'maintainer': 'Soluciones Digitales para impulsar su Negocio',
    'depends': ['account'],
    'data': [
        'views/inherit_account_move.xml',
        'security/security_grupo_account_move.xml',
        'security/ir.model.access.csv',
        'views/inherit_account_move_line.xml',
        'views/inherit_account_payment.xml',
        'views/inherit_analytic_account_view.xml',
        'views/inherit_analytic_group_view.xml',
        # 'views/inherit_account_move.xml',
        'views/pdf_viewer.xml',
        'views/historial_transaccion.xml',
        'views/rastreo_payment.xml',
        'views/account_group_view.xml',
        'wizard/cargar_saldos_contable_wizard.xml'
    ],
    'images': ['static/description/icon.png'],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': True,
}
