{
    'name': 'Modulo Inventario Mejoras',
    'version': '1.0',
    'category': 'stock',
    'summary': 'Mejoras de fecha , quitar crear y editar, adiccionar columna stock',
    'sequence': '10',
    'author': 'Sodigitalim',
    'maintainer': 'Soluciones Digitales para impulsar su Negocio',
    'depends': ['stock','stock_account'],
    'data': [
        'views/inherit_stock_picking.xml',
        'views/inherit_stock_move.xml',
        'views/inherit_stock_move_line.xml',
        'security/security_groups.xml',
        'views/inherit_product_category.xml',
        'views/inherit_product_template.xml',
        'views/inherit_stock_inventory.xml',
        'views/inherit_res_config_settings.xml',
        'reports/inherit_report_inventario.xml',
        'reports/report_comprobantes.xml',
        'reports/report_stock_picking_entrega_consignacion.xml',
        'reports/report_stock_picking_recepcion_materiales.xml',
        'reports/report_stock_picking_3.xml',
        'reports/report_stock_picking_recepcion_consignacion.xml',
        'reports/report_stock_picking_devolucion_proveedores.xml',
        'reports/report_stock_picking_devolucion_librerias.xml',
        'data/default_data.xml',
    ],
    'images': ['static/description/icon.png'],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': True,
}