{

    "name": "Modulo Route Sales",
    "version": "14.0.14",
    "development_status": "Beta",
    "category": "Generic Modules/Base",
    "author": "BanticSoftware S.R.L.",
    "depends": [
        "base",
        "account",
        # "l10n_bo_btc_facturacion",
    ],
    "summary": "Custom views for sales, contacts, other",
    "data": [
        'security/ir.model.access.csv',
        'data/data.xml',
        'report/report_menu.xml',
        'report/rp_payment_sale.xml',
        'report/rp_invoice_open.xml',
        'report/rp_invoice_open_pu.xml',
        'report/rp_cash_flow.xml',
        'wizard/wizard_get_report.xml',
        'wizard/wizard_report_open_invoice.xml',
        'wizard/wizard_report_open_invoice_pu.xml',
        'wizard/wizard_cash_flow.xml',
        'views/partner_view.xml',
        'views/partner_sale_zone_view.xml',
        'views/account_move_view.xml',
    ],
    "application": False,
    "installable": True,
    "auto_install": False,
    "license": "AGPL-3",
}
