{
    'name': 'Ocultar Campos y Botones',
    'version': '1.0',
    'category': 'Herramientas extras',
    'summary': 'Modulo para ocultar los campos Innecesarios de odoo',
    'sequence': '10',
    'author': 'Sodigitalim',
    'maintainer': 'Soluciones Digitales para Impulsar su negocio',
    'depends': ['sale','purchase','account','stock','stock_landed_costs'],
    'data': [
        'view/Venta/ocultar_confirmar.xml',
        'view/Compra/ocultar_confirmar.xml',
        'view/Venta/venta_factura.xml',
        # 'view/Inventario/Transferencia/transferencia_ocultar_campos.xml',
        'view/Compra/ocultar_crear_Factura.xml',
        # 'view/Factura/mostrar_campor_journal_id.xml',
        'view/Inventario/informe_inventario/stock_quant_quitar_permiso_escritura.xml',
        # 'view/Factura/tree_factura_modificaciones.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': True,
}   
