{
    'name': 'Valoracion del Inventario y Reprocesar',
    'version': '13.0.0.3',
    'category': 'Inventario',
    'description': """
    Este modulo tiene la funcion que permiten las mejoras de la valoracion de inventario y el Reprocesar""",
    'summary': 'Mejoras en la Valoracion del Inventario',
    'sequence': '10',
    'author': 'Sodigitalim',
    'maintainer': 'soluciones digitales para Impulsa su Negocio',
    'depends': ['stock_account'],
    'data': [
        'security/create_grupo.xml',
        'security/ir.model.access.csv',
        'wizard/wizard_reprocesar.xml',
        'view/inherit_res_config_settings.xml',
        'view/management_company.xml',
        'view/inherit_res_company.xml',
        'view/inherit_stock_location.xml',
        # 'view/inherit_stock_valuation_layer.xml',
        # 'view/inherit_menu_item_reprocesar.xml',
        # 'data/regla_resgistro.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': True,
}